### ISSUE TITLE
Should have tests for [HTMLConstructor]

### ISSUE THREAD

**Issue by bzbarsky** [w3c/web-platform-tests#10042]
I just realized today that `HTMLDialogElement` does not have `[HTMLConstructor]` in Firefox today, and apparently no test caught this.

Ideally we would check this in idlharness, but that requires being able to map from interfaces to tagnames so we can define the right custom elements, right?  @domenic @annevk

**Comment by annevk** [comment]
Yeah, though Apple objected to such an API per https://github.com/w3c/webcomponents/issues/566#issuecomment-371049783.

It seems that `custom-elements/builtin-coverage.html` tests this though, albeit conditionally which seems bad.

`dom/nodes/Node-cloneNode.html` also contains a map of local names to interfaces, which we could maybe reuse in some way rather than have that list in various places.

**Comment by bzbarsky** [comment]
> Yeah, though Apple objected to such an API

Sure.  We would basically need to hardcode a list or something.

> It seems that custom-elements/builtin-coverage.html tests this though

Ah.  That one, when run in Firefox automation, doesn't set the "enable HTMLDialogElement" pref, which is why it wasn't catching the bug.  This is good enough for my purposes, thank you!
