### ISSUE TITLE
PR dashboard rarely commenting

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#10923]
The PR dashboard has stopped commenting on most PRs since 6 April. That said, nobody has complained about it in over a month so maybe it's not very valuable?

See https://github.com/w3c/web-platform-tests/pulls?page=1&q=is%3Apr+-commenter%3Aw3c-bots+created%3A%3E2017-04-05+-status%3Apending&utf8=✓ for everything where it has failed to comment since it started being run.

It seems like this might've been its first anniversary, so did something expire?

**Comment by foolip** [comment]
@lukebjerring @jugglinmike and I have discussed this. Conclusion is that we're OK with these comments not happening, because they were not terribly actionable, and we expect the responsibility of collecting/showing PR results to move to wpt.fyi in a matter of months.

So, we should do as little as possible, but probably should remove the bit of code that notifies the PR dashboard.
