### ISSUE TITLE
Test iframe.contentDocument access for data: URL (returns null or throws exception?)

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#1480]
Same issue as https://critic.hoppipolla.co.uk/showcomment?chain=9822.

**Comment by foolip** [comment]
http://web.archive.org/web/20160402210436/https://critic.hoppipolla.co.uk/showcomment?chain=9822

PR is https://github.com/w3c/web-platform-tests/pull/1477. Searching for `git grep -lE 'iframe.*data:'` there are other tests that load data URLs in iframes. @Ms2ger, was it just *some* test that does that which you wanted to keep, to expose differences in what the origin of the documents loaded were in browser? Not sure if the interop issue still exists, needs investigation.

**Comment by Ms2ger** [comment]
I suspect I wanted some test for whatever interop issue prompted #1477. I don't think that it needs to deal with `parentNode` in particular.

**Comment by foolip** [comment]
By the title and changes in the test, then, sounds like a test for whether one can reach into `iframe.contentDocument` when the iframe src is a data URL is what's needed.

`git grep -l data: | xargs grep -l contentDocument | xargs grep -l iframe` finds these tests:
```
acid/acid3/test.html
content-security-policy/inheritance/iframe.html
css/cssom/interfaces.html
fetch/security/dangling-markup-mitigation-data-url.tentative.sub.html
html/browsers/history/the-history-interface/001.html
html/browsers/origin/origin-of-data-document.html
html/browsers/windows/nested-browsing-contexts/window-top.html
html/dom/dynamic-markup-insertion/document-write/write-active-document.html
html/dom/interfaces.https.html
html/infrastructure/urls/resolving-urls/query-encoding/resources/resolve-url.js
html/semantics/embedded-content/media-elements/loading-the-media-resource/resource-selection-invoke-insert-into-iframe.html
html/semantics/scripting-1/the-script-element/execution-timing/094.html
```

This one in particular is interesting:
https://wpt.fyi/html/browsers/origin/origin-of-data-document.html

There's a try/catch block there to mask the interop issue, so let's say this issue is about either making it unconditional in that test if we have interop now, or to fork the test to exercise only that difference.
