### ISSUE TITLE
html/semantics/document-metadata/styling/LinkStyle.html seems invalid

### ISSUE THREAD

**Issue by tkent-google** [w3c/web-platform-tests#2117]
LinkStyle.html assumes style2 and style3 have no .sheet object, and style6 has .sheet object.

```
<link id="style2" rel="alternate stylesheet" type="text/css" title="" href="./support/emptytitle.css">
<link id="style3" rel="alternate stylesheet" type="text/css" href="./support/notitle.css">
<link id="style6" rel="alternate stylesheet" type="text/css" href="./support/normal.css" title="./support/alternate.css">
```

But, I couldn't find any reasons to make the differences between them.   For UA, there is no reasons to reject missing/empty title.

@xiaojunwu

**Comment by xiaojunwu** [comment]
According to specification:

Similarly, link elements that do not represent external resource links that contribute to the styling processing model (i.e. that do not have a stylesheet keyword in their rel attribute), for which the link is an alternative stylesheet but whose title content attribute is absent or empty, or whose resource is CORS-cross-origin, must have their LinkStyle interface's sheet attribute return null.

My understanding, because that is an alternative stylesheet, usually UA may decide to represent it or not, but when the title content attribute is absent or empty, or whose resource is CORS-cross-origin, UA must not represent it.

**Comment by tkent-google** [comment]
> UA must not represent it.

What part of the specification defines it?

**Comment by rune-opera** [comment]
[1] states that the title must be non-empty. Reported https://crbug.com/692560

[1] https://html.spec.whatwg.org/multipage/semantics.html#link-type-stylesheet

**Comment by jugglinmike** [comment]
The quote that @xiaojunwu shared comes from https://dev.w3.org/html5/spec-preview/styling.html

This means the contents of the resource (or even its existence) are not a factor here. For this test, `style2` and `style3` are expected to have no `sheet` attribute because their "`title` content attribute is missing or empty", where "empty" is defined as follows:

> The term empty, when used of an attribute value, Text node, or string, means
> that the length of the text is zero (i.e. not even containing spaces or
> control characters).

(source: https://dev.w3.org/html5/spec-preview/infrastructure.html#xml)

**Comment by tkent-google** [comment]
Thanks.
The behavior is clearly defined in the W3C HTML5, and I still couldn't find it in WHATWG HTML.

Closing this anyway.
