### ISSUE TITLE
LastModified test should ignore the timezone check if the timezone changed

### ISSUE THREAD

**Issue by Manishearth** [w3c/web-platform-tests#2300]
https://github.com/w3c/web-platform-tests/blob/f685409553687752d593a435e56f87f4094c0fd9/html/dom/documents/resource-metadata-management/document-lastModified-01.html#L34

Here we check if the test matches the time zone.

We should ensure that d and initial_modified have the same time zone before running this test. Even better, construct a new date at that point and check if it has the same timezone as the old one.

If the timezones don't match (i.e. if daylight savings just happened), don't run that particular test.

**Comment by martiansideofthemoon** [comment]
I don't quite get what has to be done here @Manishearth.
> We should ensure that d and initial_modified have the same time zone before running this test.
 
Aren't we checking this in the test? Don't last_modified and initial_modified correspond to the same timestamp due to [1] ?

[1] -> https://github.com/w3c/web-platform-tests/blob/f685409553687752d593a435e56f87f4094c0fd9/html/dom/documents/resource-metadata-management/document-lastModified-01.html#L8-L9

**Comment by Manishearth** [comment]
Oh, sorry. I meant d and `new Date()`.
