### ISSUE TITLE
DOMTokenList's replace() method needs tests

### ISSUE THREAD

**Issue by annevk** [w3c/web-platform-tests#2323]
See whatwg/dom#28 for context.

**Comment by frewsxcv** [comment]
https://github.com/servo/servo/pull/9353/commits/d010df92cf104a26afebb3e5b25689bca09ed662 was just merged into Servo, so I assume it will get upstreamed here soon.

**Comment by ArkadiuszMichalski** [comment]
This test exist in [`Element.classList`](https://github.com/w3c/web-platform-tests/blob/master/dom/nodes/Element-classlist.html). It would be better to split this test separately for each method (stringifire or other cases) and put it to `web-platform-tests/dom/lists/` because now everything exist in one file and it's hard to correct anything.

**Comment by annevk** [comment]
@ArkadiuszMichalski that seems like a potential new issue or a PR that cleans things up. I'm going to close this since it seems we have some tests.
