### ISSUE TITLE
Some test files have the same filename except for the extension 

### ISSUE THREAD

**Issue by youennf** [w3c/web-platform-tests#2327]
This makes WebKit import of these tests difficult since each test file FOO.html is usually linked to a (FOO-expected.txt) expectation file which would clash with the expectation file of FOO.xhtml.
Most of these tests I am aware of are in web-platform-tests/dom/nodes.

Would it be ok to rename those test files?
Would it be ok to ensure new tests do not exhibit that?

**Comment by jgraham** [comment]
I guess my first choice would be for WebKit to have a better system for storing the metadata of the files :)

That said I would accept a patch to rename the affected files (even though it isn't ideal from the point of view of gecko because we don't track renames so we lose all the metadata), if it was accompanied by a lint to enforce your requirements.

**Comment by youennf** [comment]
Yeah, I though you woud say that ;)
Note that this might also be helpful to Chromium at some point.

I think this would end up renaming about 30 or so tests.
I will prepare a patch for it.

**Comment by youennf** [comment]
Related PRs are https://github.com/w3c/web-platform-tests/pull/2349 and https://github.com/w3c/wpt-tools/pull/40

**Comment by gsnedders** [comment]
cc/ @qyearsley

**Comment by qyearsley** [comment]
That above comment was me; I didn't realize I was accidentally logged in with the account that's supposed to be the bot account :-/

**Comment by bobholt** [comment]
Closing as resolved by https://github.com/w3c/web-platform-tests/issues/2349.
