### ISSUE TITLE
Various IndexedDB tests expect the wrong exception for aborted transactions

### ISSUE THREAD

**Issue by beidson** [w3c/web-platform-tests#2456]
Various IndexedDB tests expect the wrong exception for aborted transactions.

The following tests abort the transaction but then perform operations on an IDBIndex:
idbindex_get7.htm 
idbindex_getKey7.htm 
idbindex_openCursor2.htm 
idbindex_openKeyCursor3.htm

The test claims to be checking for TransactionInactiveError, and the spec says the function calls should throw TransactionInactiveError.

Yet the test *actually* checks for InvalidStateError.

The test should do what it claims, which would actually be correct.

**Comment by inexorabletash** [comment]
Per Ignore TRs when there's an ED.

Precedence of exceptions was undefined in the "v1" spec (the TR - http://www.w3.org/TR/IndexedDB/) - you could infer an order but it doesn't actually say to apply the rules in the order they appear - it's not written as an imperative algorithm. Sad story. But apparently we've survived thus far.

The Editor's Draft of "v2" (https://w3c.github.io/IndexedDB/) *does* attempt to define the order, although (because of the above) implementations differ. See https://github.com/w3c/IndexedDB/issues/11 which attempts to get some sanity.

Per "v2", it should be `TransactionInactiveError` in these cases, so agreed - that sounds wrong. How do implementations do? (If they all agree, we can change the spec.)

(On behalf of Chrome: if someone comprehensive implements tests that validate the precedence of exception cases when multiple clauses apply, I'll update the implementation to match! Fixing the implementation is easy, writing the tests is hard!)

**Comment by beidson** [comment]
Unlike my similar report (https://github.com/w3c/web-platform-tests/issues/2455), I think this one is purely and simply a bug in the test.

The (unspecified) precedence isn't really the problem.

You say:
> Per "v2", it should be TransactionInactiveError in these cases, so agreed - that sounds wrong.

But, per "v1" of the spec it should also be TransactionInactiveError.

The *text* of the tests claim to expect TransactionInactiveError, v1 of the spec calls for TransactionInactiveError, all implementations give TransactionInactiveError...  
...Yet the tests *actually* check for InvalidStateError.

The tests should just be fixed, right?

**Comment by inexorabletash** [comment]
Sorry, I was unclear. Agreed - if spec and implementations agree, let's fix the test.

**Comment by inexorabletash** [comment]
Okay, did some more digging.

The tests were changed in https://github.com/w3c/web-platform-tests/commit/0a5be2de9ea51afc9df3802679972d41619ee619

This was in response to discussion and updates to the ED to clarify the precedence order: if the index has been deleted (due to the tx rollback) and the transaction aborted, which exception should be thrown?

After discussion with implementers, we settled on what's now in the ED: the `InvalidStateError` takes precedent. FF was updated (test passes in FF43). Chrome has not been updated (https://crbug.com/505597).

That CL should have updated the description as well as the assertions.

Now confusingly, https://github.com/w3c/web-platform-tests/commit/1713be518d98e063170aa068858e7942e43c2e6f came in later and undid two of those changes. I don't know who approved that, but it's wrong. So the tests fail in FF43. It should be `InvalidStateError` there too.

However, to make things more confusing:

The intent of all of those tests is "throw XXXX on aborted transaction" but the test is really doing two things: aborting the transaction and deleting the index (because it's an upgrade transaction).

So there are two possible fixes here:

1. Leave test logic alone, fix titles/assertions (to be `InvalidStateError` everywhere)
2. Change the test logic to ONLY be testing the "... on aborted transaction", by aborting a non-upgrade transaction (it would be `TransactionInactiveError` everywhere)

Choice 2 is probably the right thing to do.

**Comment by beidson** [comment]
Thanks for the quick discussion and action!
