### ISSUE TITLE
Add a test for textarea.value and child text nodes

### ISSUE THREAD

**Issue by Ms2ger** [w3c/web-platform-tests#2548]
@nateps reported an inconsistency in https://github.com/whatwg/html/issues/551. We should have a test for the specified behaviour, under `html/semantics/forms/the-textarea-element/`.

If you'd like to write a test, there's documentation at http://testthewebforward.org/docs/.

**Comment by TimvdLippe** [comment]
I wanted to write my first WPT test, but I think this is already fixed by @domenic in https://github.com/w3c/web-platform-tests/commit/05679040ae1160cc30511160d3ffd123df70799d per https://github.com/whatwg/html/pull/2766

@domenic Could you confirm/deny? Would like to contribute my first test, but don't want to do double work :smile:

**Comment by domenic** [comment]
Hmm, yep, sorry I didn't see this earlier, and I'm glad you checked. Best of luck finding more good first contributions!
