### ISSUE TITLE
fetch origin referrer tests miss slash

### ISSUE THREAD

**Issue by franziskuskiefer** [w3c/web-platform-tests#2618]
The fetch origin referrer test `fetch/api/policies/referrer-origin.html` expects `http://web-platform.test:8000` as referer instead of `http://web-platform.test:8000/`.

**Comment by annevk** [comment]
It appears that specific bug has been fixed by https://github.com/w3c/web-platform-tests/commit/c8bb82a6a1495f264e394778c3e930de36c85673.

This test still has a problem however that it always expects a non-default port to be used, so http://w3c-test.org/fetch/api/policies/referrer-origin.html ends up failing for no reason (although the second test should fail since Firefox has apparently not yet relaxed its `Request` constructor).

I'm not sure how to fix the default port issue since the documentation for WPT is still broken and nobody is around on IRC to help.
