### ISSUE TITLE
websockets cookies/006.html contains logic branches for multiple run configs

### ISSUE THREAD

**Issue by bobthekingofegypt** [w3c/web-platform-tests#2728]
Looking into this test for a servo issue ( https://github.com/servo/servo/issues/9803) and I can see that it contains the logic for testing both wss and ws codepaths.  
I understood that the test suite was run through once and each test was created around a specific endpoint, be it secure or not secure.  Is this test correct or should there be a secure and an insecure version?

The constants.js file for the websocket tests also contains the fixme
```
//FIXME: Add support for wss
```
Which suggests wss isn't supported yet anyway.

cc @zcorpan

**Comment by zcorpan** [comment]
The websocket tests that Opera contributed can be run with `?wss` appended to the URL to make them run with `wss:` protocol, and I believe this worked while we ran the tests for Presto since we had a secure websocket server set up, but w3c-test.org doesn't yet and wpt-serve default setup doesn't yet, I think. cc @jgraham 

(The "top-level" tests with separate test files for Secure were submitted by MS.)

This particular test should be correct in either variant -- ws or wss. It tries to set a "Secure" cookie with document.cookie, and checks if that cookie is sent with the WebSocket open handshake. When run with `?wss` it expects the cookie to be sent; otherwise it expects it to not be sent.

So right now `?wss` is dead code, and if we get support for secure websocket server in web-platform-tests the right way of starting to run the Opera websocket tests is probably to duplicate the test files and remove the query string logic.

**Comment by jgraham** [comment]
There is a secure websockets setup and we have a (little used) mechanism for multiple tests coming from a single file using `<meta name=variant>` (c.f. https://github.com/w3c/web-platform-tests/blob/master/html/syntax/parsing/html5lib_adoption01.html#L7), so these tests probably ought to be updated to use that.
