### ISSUE TITLE
html/browsers/origin/cross-origin-objects/win-documentdomain.sub.html uses nonstandard Array.forEach

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#3611]
This is a Firefox-only extension.

/cc @annevk who appears to have created this test and @cdumez who seems to be investigating it.

**Comment by cdumez** [comment]
html/browsers/origin/cross-origin-objects/cross-origin-objects.sub.html uses forEach too

**Comment by cdumez** [comment]
Although Array.forEach seems supported by Safari.

**Comment by cdumez** [comment]
Array.prototype.forEach seems to be part of EcmaScript?
-> http://www.ecma-international.org/ecma-262/5.1/#sec-15.4.4.18

If so, I think we can close. html/browsers/origin/cross-origin-objects/cross-origin-objects.sub.html is timing out in Safari / Chrome but I have not figured out why yet but this is almost certainly not because of Array.prototype.forEach.

**Comment by domenic** [comment]
I meant specifically `Array.forEach`, not `Array.prototype.forEach`.

**Comment by cdumez** [comment]
Oops, sorry. Please disregard my previous comments then. Safari indeed does not support Array.forEach() and will fail html/browsers/origin/cross-origin-objects/win-documentdomain.sub.html as a result.

**Comment by cdumez** [comment]
Oh, and you are also right that this is the reason why html/browsers/origin/cross-origin-objects/cross-origin-objects.sub.html is timing out in Safari and Chrome but not Firefox!

**Comment by cdumez** [comment]
Can be closed.
