### ISSUE TITLE
media-source/mediasource-appendbuffer-quota-exceeded.html invalid and non spec compliant

### ISSUE THREAD

**Issue by jyavenard** [w3c/web-platform-tests#3662]
There are several assumptions taken by this test that are incorrect to start with:

1- The test must complete within 10s. The file being added is less than 200kB long. The eviction threshold could be hundreds of MB. Nothing states that it must complete within 10s when the loop could be so long

2- The test append the data in a loop and assert that the buffered range must be continuous. There are at least two issues here; the first one is that nothing in the spec defines on how eviction should occur, nor that we should never evict data in the future. The other is that the video used in the test has the video track starting slightly after the audio track. As such, the buffered range being the intersection of the audio track and video track buffered range. You will have a gap in the buffered range after the second appendBuffer. Of course you need to use a browser that correctly calculate the buffered range in the first place like Firefox. The only way to guarantee that the buffered range will be continuous will be to use a video only file.

**Comment by wolenetz** [comment]
In Chrome we have at least two variants of this test depending on which
platform is being tested, due to timeouts and the limits embedded in the
heuristic. You're right that the spec doesn't prohibit an implementation
from being perhaps overly aggressive in its coded frame eviction algorithm
and allow essentially unbounded iterations of small continuous appends. In
Chrome, we found that tailoring the heuristic to accommodate a few common
app buffering patterns reduced the need for an app to refetch/reappend
collected ranges, especially in seeking/scrubbing cases.

In light of allowance for different implementation bounds and heuristics,
should we just drop this test from the compliance suite?

**Comment by jyavenard** [comment]
What we could do for a start, is change the timeout to be of type "long", or whatever it is to be more than 10s.

And change the file being used to instead use one of the video only file.
test-v-256k-320x240-30fps-10kf is the biggest available.

I'd be interested to know the full eviction logic in chrome.
In Firefox, we've just changed it so that we only ever evict content already played, or content in the future past a discontinuity.
Up to now, we would have evicted data in the future, up to 30s from currentTime. But we received comments that it was too aggressive, and could lead to gaps in the buffered range.
Though the specs, do state that an appendBuffer, the player should check the buffered range to find out if data we evicted or not.

IMHO, eviction isn't something well managed in the spec, it's very vague. Also it is only allowed right prior adding new content.
It doesn't leave room for say new memory pressure and the UA attempting to free some memory... it would be nice for the UA to be able to evict at any time, and notify the player with an event.

I will lodge a bug with the spec on this matter shortly.

**Comment by wolenetz** [comment]
Chrome takes into account:
* Current "read from demuxer, feeding decoder" position (per each track)
* Current media playback time
* last appended buffer (per each track)
* seek target (if any)

We've seen behavior where different apps:
1) append buffers first at seek target position, then seek there
2) seek immediately to seek target position, then append buffers there

We've also seen apps (especially live streaming ones) that append buffers very close to current "play head".

In Chrome, we've modified our heuristic to be less aggressive in collecting frames which might cause stalls in these scenarios, and apps can always use an explicit remove(...) to attempt to escape the QuotaExceededError.

Please file that spec bug -- though it will be VNext necessarily. Dynamic memory pressure notifications might be the way to go. Barring that, at least allowing the app to understand: currently buffered bytes per each track (or at least per each SourceBuffer) and the current "maximum allowed bytes to buffer" similarly (though the latter might be some aggregate or per-track). As you can probably tell, getting this right is especially why this needs to be matured carefully, hence VNext. I'd be happy to collaborate on incubating something around this.  @ddorwin FYI

**Comment by wolenetz** [comment]
I'll try adjusting the test as suggested (for V1) in https://github.com/w3c/web-platform-tests/issues/3662#issuecomment-245604505. Barring that working interoperably, this is a big "quality of implementation" allowance in the spec, so suite coverage justifiably may not show interop (heuristics can vary).

**Comment by wolenetz** [comment]
@jyavenard:

> The other is that the video used in the test has the video track starting slightly after the audio track. 

This is true (audio begins at PTS 0, video begins at DTS 0 but PTS 33ms). However, that is not the cause of the gap (nor should it be, given the allowance in the spec for "jagged-start" A/V to not stall. Non-normative spec note:
"NOTE
For the purposes of determining if HTMLMediaElement.buffered contains a TimeRange that includes the current playback position, implementations may choose to allow a current playback position at or after presentation start time and before the first TimeRange to play the first TimeRange if that TimeRange starts within a reasonably short time, like 1 second, after presentation start time. This allowance accommodates the reality that muxed streams commonly do not begin all tracks precisely at presentation start time. Implementations must report the actual buffered range, regardless of this allowance."

In Chrome, though, we still incorrectly yield a buffered range gap for the isobmff version (and if this is due to PTS/DTS conflation, this is a known issue). It looks like it's a known issue.

**Comment by wolenetz** [comment]
Using a single track SourceBuffer for this test does make sense because
sequence mode muxed appends don't really make sense in the first place.

**Comment by jyavenard** [comment]
@wolenetz 
> However, that is not the cause of the gap (nor should it be, given the allowance in the spec for "jagged-start" A/V to not stall. 

I read it entirely differently, and yes it does cause the gap as:
>  Implementations must report the actual buffered range, regardless of this allowance."

so the allowance for playback has no impact on what's actually reported. The gap is small here, it doesn't affect playback. But the buffered range reported will show the gaps.
The test asserts that buffered.length is 1, it won't be.

> Using a single track SourceBuffer for this test does make sense because sequence mode muxed appends don't really make sense in the first place.

totally agree. And we should change the sequence mode test too.. but that's another topic :)

**Comment by wolenetz** [comment]
> I read it entirely differently, and yes it does cause the gap as:

Yes, the buffered ranges (which are intersection of A & V in this case) should report correctly a gap *at the beginning* of the timeline. But still just 1 buffered range if sequence mode append is used throughout. Muxed A/V and sequence is less-tested and therefore less sane, so gaps later in the timeline might occur due to muxed A/V sequence mode implementation bugs, and those gaps would show up in the intersection ranges reported by {HTMLMediaElement,SourceBuffer}.buffered, too. I know I'm being a little pedantic here, and maybe we're saying the same thing, but I don't think the spec text I quoted in https://github.com/w3c/web-platform-tests/issues/3662#issuecomment-245708839 is responsible for any occurrence of *multiple* buffered ranges in this test.

**Comment by jyavenard** [comment]
The gaps in the buffered range is due to how the sequence mode is defined.
When adding in sequence mode,
https://w3c.github.io/media-source/index.html#sourcebuffer-coded-frame-processing, step 3.

```
If mode equals "sequence" and group start timestamp is set, then run the following steps:
    Set timestampOffset equal to group start timestamp - presentation timestamp.
    Set group end timestamp equal to group start timestamp.
    Set the need random access point flag on all track buffers to true.
    Unset group start timestamp.
```
 timestampOffset will be adjusted to the first timestamp seen from the 2nd appendBuffer (as it's the first discontinuity seen); which here would be from the audio track. It then continues to add samples to the track buffer.
So the first video sample will be added with the same delay from the first audio sample.
the gap is there, and the buffered range should report it, between each segment added.

Getting continuous buffered range when using sequence mode with media containing both audio and video, when one track doesn't start exactly where the other track starts, can't be achieved.

**Comment by wolenetz** [comment]
Yeah, the spec leaves a little grey area there: since sequence mode's
"discontinuity detection" is triggered on one of the two tracks, all "last
decode timestamps" are reset, so discontinuity isn't detected on the first
frame in the *other* track even if it is > 2*last_frame_duration in the
future (or even into the past) vs the last "buffered" decode timestamp for
that other track. Hence, strict reading of the spec indicates there might
not be a buffered range gap there in implementations. That's unfortunate
and a known consequence of using muxed tracks in 'sequence' mode appends.
