### ISSUE TITLE
[eme] Return NOTRUN when failure is not due to implementation under test

### ISSUE THREAD

**Issue by mwatson2** [w3c/web-platform-tests#3735]
When a test cannot complete successfully for a reason that is not the fault of the implementation under test, the test should return NOTRUN. Such reasons include:
- optional features not supported by the implementation
- server failures
- others ?

A test returns NOTRUN if test.done() is called without any assertions being tested.

**Comment by ddorwin** [comment]
FYI, I believe the indication of NOTRUN is very subtle in the test report.

For example, while running the persistent-license tests, the test runner shows a blue NOTRUN in the results, but the JSON says there was a timeout. in http://w3c.github.io/test-results/encrypted-media/all.html, there appears to be a subtle difference. The NOTRUN test has a TIMEOUT in the test name row while regular timeouts show TIMEOUT there and in the individual test case.

Maybe we should file a bug against the framework. Also, it might be worth requesting an explicit way to fail a test for external reasons rather than having to ensure no assertions were checked.

**Comment by ddorwin** [comment]
`NOTRUN` might be ambiguous with unsupported features if we decide to use it for #3765.

**Comment by louaybassbouss** [comment]
unsupported mandatory features should fail

**Comment by mwatson2** [comment]
What about unsupported option features ?

**Comment by mwatson2** [comment]
This duplicates #3765
