### ISSUE TITLE
[eme] drm-mp4-playback-temporary-multikey-sequential.html times out due to missing duration

### ISSUE THREAD

**Issue by ddorwin** [w3c/web-platform-tests#3915]
drm-mp4-playback-temporary-multikey-sequential.html is timing out on all three browsers.

We found that `config.duration` is `undefined` in `onTimeupdate()`. Two issues:
 1. drm-mp4-playback-temporary-multikey-sequential.html does not specify `duration` like its peer, clearkey-mp4-playback-temporary-multikey-sequential.html.
 1. playback-temporary-multikey-sequential.js does not have `|| 0.5` like, for example, playback-temporary-encrypted-clear-sources.js.

More generally, why do any of the existing HTML files specify a duration? None of them are doing anything that requires an override.

**Comment by mwatson2** [comment]
There are three kinds of test where the duration needs to be longer than a second or so. These are where we need to ensure playback continues through some transition. In the case of the multikey-sequential tests, its a transition through different keys, in the clear-encrypted test from clear to encrypted and in the encrypted-clear test the opposite. All of these should have durations configured (as this depends on the content) and the rest of the tests should use the default 1s.

Adding the durations to the multikey-sequential tests causes them to sometimes pass on Chrome and always fail on Firefox / Edge. The instability on Chrome is because of the timing of the waitingforkey event. Sometimes Chrome sends this early, which is a failure (it should not be sent until playback pauses - see [here](https://w3c.github.io/encrypted-media/#dom-evt-waitingforkey)). Sometimes it is sent later, and then the test passes.

**Comment by mwatson2** [comment]
PR #3916

**Comment by mwatson2** [comment]
I filed #3917 for the instability of the test on Chrome.

**Comment by ddorwin** [comment]
Don't those tests also have different JS files to implement and/or check the transition? It seems that having the external (in .html files) duration could cause bugs.

Thanks for filing the other issue. We'll look into it.

**Comment by mwatson2** [comment]
I think actually the other issue was a test issue and I've proposed an update to the test.

My guess is that there is a race between the media processing and the license acquisition. If the former is faster, you get a waitingforkey event right at the start. This is valid, but in the test it triggers the second license acquisition.

What I'm proposing is to move the attaching of the media source until after the license acquisition to avoid this race.
