### ISSUE TITLE
[eme] Tests should FAIL rather than TIMEOUT when a feature is not supported

### ISSUE THREAD

**Issue by ddorwin** [w3c/web-platform-tests#3938]
We should only see `TIMEOUT` in the results if the test did not complete, such as an event never fired. Otherwise, the tests should be `FAIL`. This makes it clearer that the test ran to some completion and differentiates from, for example, test problems. Timeouts are also harder to investigate since there is not clear failing assert in the test output.

Currently, the tests for the optional persistent session types show `TIMEOUT` for all browsers. At least for browsers that do not support them, these should be `FAIL`. We might want to look at other remaining `TIMEOUT` results after the next results update.

**Comment by mwatson2** [comment]
A lot of the time, Promise rejections are passed to forceTestFailureFromPromise which causes a TIMEOUT. We could change some of these to assert_unreached to achieve what you suggest.

**Comment by mwatson2** [comment]
It appears that we could just replace the call to `forceTestFailureFromPromise` with an `assert_unreached` (wrapped in a `step-func`) and then we get `FAIL` rather than `TIMEOUT`.

I'm not sure now why the `forceTestFailureFromPromise` approach is used at all. It was inherited from the Google tests. Does anyone have any insight ?

**Comment by mwatson2** [comment]
PR #4023 appears to work, but I do not fully understand the comment in `forceTestFailureFromPromise`, so I may be missing something.

**Comment by jrummell-chromium** [comment]
When we started the Chrome tests, there was no promise_test functionality in the test framework, so all the tests were async_tests. When an error was detected (e.g. an unexpected event) the test would simply waste time waiting for the test timeout to occur (which was 30 or 40 seconds). This was an attempt to make the test stop as soon as an error was detected.

From what I recall, calling test.done() was the only way to stop the test (without waiting for the actual timeout). The only public way to set the status to something other than SUCCESS was test.force_timeout(), so that was used. For Chrome we only care if the test succeeds or not, so any status other than SUCCESS is a failure.

So if assert_unreached (wrapped in a step-func) works, and gives a the desired FAIL result, there should be no problem changing forceTestFailureFromPromise() to do that.

**Comment by mwatson2** [comment]
On Wed, Oct 19, 2016 at 2:24 PM, jrummell-chromium <notifications@github.com
> wrote:

> When we started the Chrome tests, there was no promise_test functionality
> in the test framework, so all the tests were async_tests. When an error was
> detected (e.g. an unexpected event) the test would simply waste time
> waiting for the test timeout to occur (which was 30 or 40 seconds). This
> was an attempt to make the test stop as soon as an error was detected.
>
> From what I recall, calling test.done() was the only way to stop the test
> (without waiting for the actual timeout). The only public way to set the
> status to something other than SUCCESS was test.force_timeout(), so that
> was used. For Chrome we only care if the test succeeds or not, so any
> status other than SUCCESS is a failure.
>
> So if assert_unreached (wrapped in a step
> ​_​
> func) works, and gives a the desired FAIL result, there should be no
> problem changing forceTestFailureFromPromise() to do that.
>
> ​Ok, makes sense. ​Looking at the test harness, what assert_unreached
(wrapped in a step_func) actually does is set the state of the test to FAIL
and then call test.done().

...Mark
