### ISSUE TITLE
[eme] createSession('persistent-license') failures not handled properly

### ISSUE THREAD

**Issue by jrummell-chromium** [w3c/web-platform-tests#4029]
The test https://w3c-test.org/encrypted-media/clearkey-mp4-syntax-mediakeysession.html is failing on Chrome 56.0.2895.0 (latest canary build) with:
```
promise_test: Unhandled rejection with value:
object "NotSupportedError: Failed to execute 'createSession' on 'MediaKeys': Unsupported session type."
```
The problem appears to be function test_generateRequest() which calls:
```
var mediaKeySession = testCase.func.call(null, mediaKeys);
```
where testCase.func is "return mk.createSession('persistent-license');" Since createSession() doesn't create a promise, it throws NotSupportedError on unsupported session types, which is not caught, and thus the promise_test fails.

Chrome tests have 
```
    function test_generateRequest(testCase, mediaKeys, type, initData)
    {
        try {
            var mediaKeySession = testCase.func.call(null, mediaKeys);
            return mediaKeySession.generateRequest(type, initData);
        } catch (e) {
            assert_true(testCase.isNotSupportedAllowed);
        }
    }
```
For completeness it probably needs something like "assert_equals(e.name, "NotSupportedError"); return Promise.resolve(e);" in the catch block so that a promise is always returned from the function on success.

**Comment by ddorwin** [comment]
PR #4059

**Comment by ddorwin** [comment]
@cpearce, it appears Firefox nightly was passing before this change. Using the test before this change, it appears Firefox incorrectly does not throw an exception for `createSession("persistent-license")` (see the first step of https://w3c.github.io/encrypted-media/#dom-mediakeys-createsession) then fails with an `InvalidAccessError` related to the initData. I think Firefox will fail with this PR since it expects the exception from `createSession()`.

While not directly related, I don't believe `InvalidAccessError` should probably never be returned by EME APIs. All instances were replaced by `TypeError`.
