### ISSUE TITLE
wpt-stability-bot feedback

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#4056]
wpt-stability-bot is amazing! Some minor things that would make it more amazing:

- Instead of a whole column for test, which is often empty, just use the test filename and overall results as a subheading; then you can do a two-column table and everything is less squished
- Translate the "OK: 10" "FAIL: 10" "PASS: 10" into something comprehensible. Maybe just removing the ": 10"?
- When writing the test filenames, make them links to their w3c-test.org/submissions/ versions
- Remove "files changed"? It seems redundant with what GitHub already provides.
- Say which commit hash is being tested.

**Comment by jgraham** [comment]
> *   Instead of a whole column for test, which is often empty, just use the test filename and overall results as a subheading; then you can do a two-column table and everything is less squished

Hmm. We could probably manage with the filename as a subheading and the parent result in the table with an empty subtest name or similar. Putting the result in the heading sounds weird.

> *    Translate the "OK: 10" "FAIL: 10" "PASS: 10" into something comprehensible. Maybe just removing the ": 10"?

Just in the case where it matches the number of iterations? I suppose that might work. In general there's an issue that subtests might not even run sometimes so `PASS: 3` wouldn't count as stable.

> * When writing the test filenames, make them links to their w3c-test.org/submissions/ versions

Yeah, we discussed that this morning. The problem is that those files don't always exist, unless you are a contributor or did the `w3c-test: mirror` dance. So someone would end up explaining to people why the links were 404.

 > * Remove "files changed"? It seems redundant with what GitHub already provides.

Agreed, that was for debugging.

> * Say which commit hash is being tested.

Sounds reasonable.

**Comment by domenic** [comment]
Ah, I had no idea the ": 10"s were number of successful/failed runs. I thought they were error codes or something. Yeah, omitting them when they're 10 makes sense. Otherwise, maybe "PASS (3/10 runs)" or "PASS (4/10 runs) FAIL (6/10)" would do the trick.

**Comment by jgraham** [comment]
Is the output at the bottom of https://github.com/w3c/web-platform-tests/pull/4055 an improvement?

**Comment by domenic** [comment]
The current output is great, thank you!
