### ISSUE TITLE
Could we make ./serve update submodules

### ISSUE THREAD

**Issue by annevk** [w3c/web-platform-tests#4621]
Alternatively, I'm willing to provide a pull request to add a Makefile where when you run make it updates submodules. I can never remember the command.

**Comment by bobholt** [comment]
This is probably less of an issue now that most submodules are part of the repo, but we do still have a few:

```
submodule.css/tools/apiclient.path
submodule.css/tools/w3ctestlib.path
submodule.tools/html5lib/html5lib/tests/testdata.path
submodule.resources/webidl2/test/widlproc.path
```

I'm not fond of adding that functionality to `./serve`, and I don't think we're using Makefiles anywhere else, so that would add another level of language diversity to the repo (which we already hear about with Python and JS).

This could be a bash/Python shell script. I think bash would just be:

``` bash
#!/bin/bash
git submodule update --init --recursive
```

Python would be something like:

```
#!/usr/bin/env python
import subprocess
subprocess.call(["git", "submodule", "update", "--init", "--recursive"])
```

Thoughts @jgraham?

**Comment by jgraham** [comment]
I think this is unneeded now we monoreppoed everything that's actually required.
