### ISSUE TITLE
[presentation-api] presentation URLs for receiving user agent test cases

### ISSUE THREAD

**Issue by tomoyukilabs** [w3c/web-platform-tests#4991]
Currently, test cases for controlling user agent use a shared presentation URLs defined in common.js, which consist of a couple of URLs: "support/presentation.html" and a URL with Cast App ID maintained by W3C team, for 2-UA mode of Chrome.

I wonder whether test cases for receiving user agent should also share the same presentation URLs or not. If so, any test cases as well as idlharness.html must be integrated into a single HTML file. Otherwise, while we can implement each test case as a separate file, each one may require a different Cast App ID. WDYT?

**Comment by tomoyukilabs** [comment]
Cc: @tidoust @louaybassbouss

**Comment by tidoust** [comment]
That is a good question, @tomoyukilabs !

I do not think we should structure our receiving tests because of existing restrictions in Cast devices. Ideally, Cast App IDs will disappear from the test suite in the end. I can create as many Cast App IDs as necessary in the meantime, although I realize it's not very convenient for running tests locally (or from a  server different from `w3c-test.org`).

We should probably favor test automation. By definition, receiving tests need to be initiated by a controlling page, so there needs to be a call to `start` somewhere, which requires human interaction, but grouping receiving tests together would reduce the number of manual tests in the test suite. I don't think we should go too far though. I would keep IDL tests separated from other tests for instance. Also, it seems cleaner to separate tests that check very different aspects...

All in all, I don't know :) My gut feeling would be to create separate test files to start with and adjust afterwards if we find a better way to structure tests, but feel free to proceed as you see fit. I'll create Cast App IDs as needed.

Somewhat related: do you know how you're going to report test results? Ideally, after the call to `start`, the controlling page would be able to report the test result automatically to the test runner, but that means the test result needs to travel from the receiving side to the controlling side (through some mechanism à la `stash.py`). Or the test result remains on the receiving side, but that means the tester needs to report the result manually.

**Comment by tomoyukilabs** [comment]
Thanks for your comments, @tidoust! For now, I consider implementing each tests as a separate file. Of course, I agree that Cast App IDs will finally become unnecessary.

Also, I am investigating how a receiving page can notify its results of a controlling page. My current idea is like the following:

* A receiving page can obtain its test results from a callback mechanism `add_completion_callback()`.
* The test results can travel through a mechanism like `stash.py`.
* A controlling page can notify the test results of the test runner by calling `window.opener.completion_callback()`.
* However, there is no means to deserialize the test results obtained by the callback. For now, I am considering passing `innerHTML` of the receiving side's log to the controlling side as it is.

I would be pleased if anyone could find a better way.
