### ISSUE TITLE
[presentation-api] test for defaultRequest doesn't invoke it

### ISSUE THREAD

**Issue by ltetzlaff** [w3c/web-platform-tests#5031]
The test https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/defaultRequest_success-manual.html can't pass since the "onconnectionavailable"-event is only fired after Point 3 of https://w3c.github.io/presentation-api/#starting-a-presentation-from-a-default-presentation-request was executed.

The only possible implementation that i can think of that passes this test may be a setter function on `navigator.presentation.defaultRequest` that automatically executes the procedure above which then again breaks this requirement:
> The controlling user agent should initiate presentation using the default presentation request only when the user has expressed an intention to do so via a user gesture, for example by clicking a button in the browser chrome.
(https://w3c.github.io/presentation-api/#controlling-user-agent )

**Comment by tidoust** [comment]
@ltetzlaff As far as I can tell, the test works as intended. This test checks the "default request" feature that user agents may implement (it seems to be the case in Chrome Canary for instance).

That feature allows a user agent to expose something like a "Cast" button which, when pressed, will start the `PresentationRequest` that the app may have set on `navigator.presentation.defaultRequest`.

By definition, an app (and thus the test) cannot control this Cast button, because it belongs to the chrome of the user agent. That's the reason why the test starts by asking the user to click the Cast button. This should start the presentation, and eventually fire the `connectionavailable` event.

Am I missing something?

**Comment by ltetzlaff** [comment]
Hi @tidoust ,
thanks for the comprehensive explanation - my bad then.
I wasn't aware that this effectively bypasses the steps https://w3c.github.io/presentation-api/#dom-presentationrequest-start if the user was to initiate the start of the presentation through the browser chrome (because they aren't necessary then).
