### ISSUE TITLE
Spec links to TR vs to EDs, numbered vs unnumbered shortnames, which level, etc

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#5292]
Originally posted as https://github.com/gsnedders/wpt-docs/issues/5 by @frivoal on 09 Jan 2017, 01:06 UTC:

> I don't remember the exact rules, but I believe that there are constraints on which URLs you can use in [spec links](https://gsnedders.github.io/wpt-docs/writing-tests/css-metadata#specification-links). These should be documented.
> 
> While we're at it, we may also want to (agree on and) document the best practices when it comes to which level of a spec you should link to when you have a choice. Say you're writing a test for the interaction between FOO which is new and only exists in css-foo-1 and BAR which exists in CSS2.1 and css-bar-3 and css-bar-4. There's no question of which FOO you should link to, but for bar there is. Same question when you're writing tests for css-baz-3, and realize that some of the things you're testing were already defined in CSS2.1. Do you link to css-baz-3, CSS2.1, or both?
> 
> I don't believe this is an area that should have tooling-enforced MUSTs, but it is not useful to let tests authors be creative about that, at least in the general case. Documenting the expected practice as a SHOULD would be good.

**Comment by gsnedders** [comment]
Originally posted as https://github.com/gsnedders/wpt-docs/issues/5#issuecomment-271299135 by @gsnedders on 09 Jan 2017, 14:35 UTC:

> Right, this is something that's likely undocumented given most of the docs were written around the time the big push on the 2.1 testsuite was happening and hence the answer 99% of the time was obvious (the 2.1 testsuite!), and much of the work since has been for wpt where versioning is solved by always testing the version of the spec we expect people to implement.

**Comment by gsnedders** [comment]
Originally posted as https://github.com/gsnedders/wpt-docs/issues/5#issuecomment-271299730 by @frivoal on 09 Jan 2017, 14:38 UTC:

> > much of the work since has been for wpt where versioning is solved by always testing the version of the spec we expect people to implement.
> 
> This seems reasonable, so it should be documented.
> 
> Also, TR or ED? TR if possible, ED if not?
> 
> And must use the numbered short-name, right?

**Comment by gsnedders** [comment]
Originally posted as https://github.com/gsnedders/wpt-docs/issues/5#issuecomment-271300204 by @gsnedders on 09 Jan 2017, 14:40 UTC:

> I don't think there's been consistency in what people have been doing TR v. ED wise. I also don't think it matters.
> 
> Numbered short-name is a requirement, yes. I'd love if someone worked out which short-names were acceptable based on `tr.rdf`.

**Comment by gsnedders** [comment]
Some of the original issue is gone since we got rid of versions, with the exception of CSS2.

The other half of it is https://github.com/w3c/web-platform-tests/issues/10288 I think?

**Comment by foolip** [comment]
Sure, let's close in favor of https://github.com/w3c/web-platform-tests/issues/10288

**Comment by frivoal** [comment]
Actually, it's not quite clear that this is resolved. For directories, we got rid of versions, and that is good.

* This does not tell us whether we should point to TR or to the ED
* For spec links, shepherd currently only supports leveled names. I presume this is in order to map it back to the correct section of that spec. This mapping is useful when looking for tests that pertain to a particular section of a particular spec. I suppose making it capable of using the unversioned shortlink is possible, but since which spec this point to may change over time, that doesn't sound all that great.

Here's what I would suggest as a best practice
1. At the time of writing the test, the test author must link to the leveled shortname, and should do so for all the specs that define the feature and that are not yet REC. They may also link to RECs if they feel like it, but that is neither necessary for regression testing nor for TR advancement, so there's no expectation that it needs to be done.
2. When starting a new level of a spec, the Editor(s) should add links to existing tests that are relevant to the new level. They should not remove/replace the existing links.
3. For any particular level, if the feature being tested is already available on TR, the test author should link to that, as it tends to be more stable in the long term. However, linking to EDs is also OK.

I think the only lint we should have is to make sure that people used leveled links. I got caught by this recently in https://github.com/w3c/web-platform-tests/pull/10934, when I was surprised that I could not find any test in the shepherd test suite, even though I knew I hard written some.

**Comment by gsnedders** [comment]
> At the time of writing the test, the test author must link to the leveled shortname

This would be solved by #10288, by actually explicitly whitelisting URLs.

> and should do so for all the specs that define the feature and that are not yet REC

Realistically, I don't think people will do this: they'll add a link to the ED they're reading, and not add any other URLs (i.e., they won't see it as beneficial to spend their time looking through each versioned spec to see if their test also applies there, especially when the text could be dramatically different—esp. in CSS2). I mean, sure, we can say people should do this—but I have no expectation it'll ever happen.

> For any particular level, if the feature being tested is already available on TR, the test author should link to that, as it tends to be more stable in the long term. However, linking to EDs is also OK.

Given we ask implementers to look at EDs (and try and tell them not to look at TR, given we've at various times had people implement from years old dated TRs), for the same reason as above, I don't think they're going to start digging through multiple versions of a spec. I think they'll link to where they're looking and that's that.

> I got caught by this recently in #10934, when I was surprised that I could not find any test in the shepherd test suite, even though I knew I hard written some.

Note even with #10288 fixed it still wouldn't guarantee the test appears in the test harness, given we don't assert that anchors exist (given to do so would make it possible for the lint to start failing without any test changes).

**Comment by gsnedders** [comment]
For the anchors case, I guess we could occasionally import the anchors DB JSON into the WPT repo and check against that stable list of anchors, but that'll likely be annoying when someone wants to write tests along with adding a new section to the spec, given it would fail the lint until the spec change has landed and the anchors DB has been updated.

**Comment by frivoal** [comment]
> This would be solved by #10288, by actually explicitly whitelisting URLs.

So we would whitelist leveld urls? Sounds good to me. Btw, where to we get the whitelist from (in other words, are you likely to run into a gap in the white list every time you start the test suite for a new spec, or is that handled automatically)?

> Realistically, I don't think people will do this: they'll add a link to the ED they're reading, and not add any other URLs

Typically, that should be enough. Most features are not being defined in multiple levels simultaneously. For those that are, having links to all the levels is preferable, but we need not block on that (hence should rather than must in my formulation).

>Given we ask implementers to look at EDs and try and tell them not to look at TR [...]I think they'll link to where they're looking and that's that.

That's OK with me. I just think we need to have a clear guidance, so that boby wastes time coming up with independent answers to that question. I can live with any of the following, and possibly more
* Link to TR if it's there, to ED otherwise
* Link to TR if it's there and you can be bothered, but EDs are fine too
* Link to EDs (or to TR if it's there and you prefer that)

I don't think we should ban linking to TR.

> Note even with #10288 fixed it still wouldn't guarantee the test appears in the test harness, given we don't assert that anchors exist

I don't think this is as important. A lint for that as well seems nice, but secondary. We can totally deal with that later.

**Comment by foolip** [comment]
@frivoal, in conclusion, do you think that there is any technical work here beyond https://github.com/w3c/web-platform-tests/issues/10288?

**Comment by frivoal** [comment]
No, the rest is just documenting what the best practice is.

**Comment by foolip** [comment]
OK, I'll leave this closed and comment to that effect on the other issue.
