### ISSUE TITLE
Shared worker tests no longer work

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#5568]
I'm going to guess this is based on some of the recent work @jgraham has done in idlharness.js?

Example: http://w3c-test.org/streams/count-queuing-strategy.sharedworker.html used to work, now it just times out.

**Comment by domenic** [comment]
This regressed in https://github.com/w3c/testharness.js/commit/39051c95cc5e9bdbc3788b7595bab9b8781e46e5. /cc @sfuqua, sorry @jgraham for blaming you, you're just the committer.

**Comment by gsnedders** [comment]
cc/ @jugglinmike given you were talking about testing this stuff

**Comment by sfuqua** [comment]
Thanks for the ping @domenic. I debugged this and it looks like it's because the SharedWorker MessagePort is no longer getting started, probably because my changed switched from `onmessage` to `addEventListener`. I tried manually calling `start()` and it looks like the test is passing again.

I think we can just move back to onmessage to fix this.

**Comment by annevk** [comment]
Yeah, you either need to invoke `start()` or use `onmessage` to call it implicitly. It's a very error prone API unfortunately.
