### ISSUE TITLE
// META comment positioning is a bit overly restrictive

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#5592]
I spent a good ten minutes scratching my head as to why this didn't work:

```js
"use strict";
// META: script=/IndexedDB/support.js

async_test(t => {
  const openReq = createdb(t);

  openReq.onupgradeneeded = e => {
    const db = e.target.result;
......
```

The reason is that `"use strict";` is above the `// META` comment.

It would be ideal to loosen this restriction a bit, or maybe fail the test if there are META comments but they are not the first line in the file.

**Comment by bobholt** [comment]
It looks like there's a 'STRAY-METADATA' check in the lint script, but it [only checks for `timeout` META, not `script`](https://github.com/w3c/web-platform-tests/blob/master/tools/lint/tests/test_file_lints.py#L491). Would having the linter catch this be sufficient?

**Comment by domenic** [comment]
Sure.

**Comment by annevk** [comment]
It would still be nice to have a way to do "use strict" though, but maybe that should be a separate issue?

**Comment by domenic** [comment]
You can just do it after the comment. It's an unusual style but still works.

**Comment by annevk** [comment]
Even if the comment ends up becoming `importScripts()` or some such in the generated resource? Interesting.

**Comment by domenic** [comment]
Oh, fair point, I didn't think about how it was implemented.

**Comment by jugglinmike** [comment]
I believe everything is working as intended, and that this issue may be closed.

When it comes to linting, [the linter is already configured to report "stray" `META` JavaScript comments](https://github.com/w3c/web-platform-tests/blob/c8c37e7ba5ce8faed4c6ca68fc07ad96f886ff93/tools/lint/lint.py#L572-L573):

```python
if meta_re.match(line):
    errors.append(("STRAY-METADATA", "Metadata comments should start the file", path, idx + 1))
```

...[regardless of the type](https://github.com/w3c/web-platform-tests/blob/c8c37e7ba5ce8faed4c6ca68fc07ad96f886ff93/tools/manifest/sourcefile.py#L19):

```python
js_meta_re = re.compile(b"//\s*META:\s*(\w*)=(.*)$")
```

[The tests that @bobholt referenced only contain a case for `timeout` metadata](https://github.com/w3c/web-platform-tests/blob/c8c37e7ba5ce8faed4c6ca68fc07ad96f886ff93/tools/lint/tests/test_file_lints.py#L491), but I've verified locally that the behavior matches the above interpretation--"stray" `script` metadata also produces warnings.

When it comes to [@annekv's point about the use of directive prologues](https://github.com/w3c/web-platform-tests/issues/5592#issuecomment-302752042), I think we're also covered there. That's because in worker contexts, [the entry point is entirely synthetic, and the "multi-global" file is executed as-is via a dedicated `importScripts` invocation](https://github.com/w3c/web-platform-tests/blob/c8c37e7ba5ce8faed4c6ca68fc07ad96f886ff93/tools/serve/serve.py#L171-L189).

If anyone on this thread could take a moment to verify all this, then I would be happy to close the issue.

**Comment by domenic** [comment]
I'm happy to accept your investigation and re-open in the unlikely event I discover it to be flawed in the future :).
