### ISSUE TITLE
Investigate failure of cssom-view/cssom-view/media-query-list-interface.xht

### ISSUE THREAD

**Issue by fred-wang** [w3c/web-platform-tests#5672]
http://w3c-test.org/cssom-view/cssom-view/media-query-list-interface.xht fails for me in Gecko, Chromium and WebKit.

cc @zcorpan

**Comment by jdm** [comment]
The first test fails because method on the global object are own properties rather than defined on the prototype [per WebIDL](https://heycam.github.io/webidl/#Global). Since this test also sets the `mediaQueryList` variable that the subsequent tests require, they also fail because the first test threw an exception.

**Comment by fred-wang** [comment]
@jdm Right, and MediaQueryList properties are actually inherited:

https://drafts.csswg.org/cssom-view/#extensions-to-the-window-interface
https://drafts.csswg.org/cssom-view/#the-mediaquerylist-interface

I'll open a PR
