### ISSUE TITLE
WPT tests may contain too many subtests

### ISSUE THREAD

**Issue by youennf** [w3c/web-platform-tests#5910]
Some WPT tests have lots of subtest.
In the context of WebKit, one flaky subtest is ruining the whole set of tests.
One timing-out sub test is doing the same.
Limiting the number of subtests or providing guidelines to limit the number of subtests would help.

**Comment by annevk** [comment]
I think it would be better to get a Safari TP bot running somehow. That way flaky behavior can be discovered when the test is created.

**Comment by youennf** [comment]
Agreed it would be cool to have STP on board. 

That said, WebKit infra is more sensitive to flakiness than the wpt bots: results log console error messages as well as failing assertions. Often flakiness comes from these. Probably something that can be added to the stability bots.

Having too many async tests was also an issue. Promise_test are better but if one is timing out, all others are also.

Some tests like interface.html were skipped as they were taking too long.

I am not advocating for one test per file. Just that a balance be found between ease of authoring and ease of running.

**Comment by annevk** [comment]
> That said, WebKit infra is more sensitive to flakiness than the wpt bots: results log console error messages as well as failing assertions.

Chrome had that too. They ended up fixing their infrastructure.

I've no good ideas on long tests. E.g., I've found there's upward of 30000 interesting IDNA tests, but I haven't found a decent way to split those in buckets yet, other than something arbitrary (and generating a file for each seems excessive).

**Comment by youennf** [comment]
> Chrome had that too. They ended up fixing their infrastructure.

In case of WebKit, this is on purpose, to catch more regressions.
WebKit infra has ways to remove console logs and assertion messages when needed.
But this is the exception, not the default. And I doubt it will ever become the default.

> I've no good ideas on long tests. E.g., I've found there's upward of 30000 interesting IDNA tests, but I haven't found a decent way to split those in buckets yet, other than something arbitrary (and generating a file for each seems excessive).

It is true that grouping tests in a file helps organizing test suite, which is an important aspect to keep WPT healthy.

**Comment by annevk** [comment]
> In case of WebKit, this is on purpose, to catch more regressions.

Sure, but if they end up making a test flaky, they become problematic as you've seen. And rewriting tests to account for that seems wrong, since that might hide problems in other browsers the test was previously catching. That's why we need to agree on which of the output of web-platform-tests is important and which is internal (and might end up being flaky).

**Comment by jgraham** [comment]
So for web platform tests the contract is that you can rely on the test title and the result, but anything else can vary (e.g. test order, other random stuff that the browser chooses to write to the console, etc.) Yes, this means that there can be regressions that you won't catch with wpt that you might have caught otherwise. But it's a fundamental part of cross-browser testing that tests, including success conditions, can only depend on standard features, not on browser-specific APIs.

I don't know what a STP bot is, but we will add Safari support to Travis via Saucelabs soon. It's not ideal, but it does work for testing in the latest released version.

I don't see any reasonable way to make number of tests more than author judgment. We have the ability to mark individual subtests as disabled (which basically means ignoring the result), but it is true that it's much easier to disable an entire file.

**Comment by youennf** [comment]
STP is Safari Tech Preview.

Console log is a specific thing for browsers, I agree this source of flakiness should be dealt by the browser environments.

I disagree for failing assertions on the other side, there is nothing browser specific here.
The only reason between assert_true(a === b) and assert_equals(a, b) is the message that can be used for debugging purposes. I think it is fine asking to use the first when it makes tests flaky in a browser.
For Safari bot, it would make sense to do these checks.

**Comment by youennf** [comment]
> In case of WebKit, this is on purpose, to catch more regressions.
> Sure, but if they end up making a test flaky, they become problematic as you've seen. And rewriting tests to account for that seems wrong, since that might hide problems in other browsers the test was previously catching. That's why we need to agree on which of the output of web-platform-tests is important and which is internal (and might end up being flaky).

These failing assertions make test flaky usually only because of an assertion error message that changes for each run, like trying to assert_equals with a dynamic token.

**Comment by annevk** [comment]
> These failing assertions make test flaky usually only because of an assertion error message that changes for each run, like trying to assert_equals with a dynamic token.

I guess I'd have to see concrete examples of before and after to judge the impact of making this go away.

**Comment by jgraham** [comment]
> These failing assertions make test flaky usually only because of an assertion error message that changes for each run, like trying to assert_equals with a dynamic token.

I don't think that will work. Consider almost any use of `assert_greater_than` or `assert_less_than`. These are always used because it's not exactly clear what the result should be but there's a known bound.

Experience suggests that even getting people to make test titles stable isn't always straightforward. This stuff is also impossible to lint. I strongly recommend not trying to impose additional constraints beyond "did the test pass" because I think the consequences are non-trivial and impose a burden on all other authors/users of the testsuite.

**Comment by bobholt** [comment]
This sounds like a will not fix. If that's incorrect, please reopen with new comments.
