### ISSUE TITLE
Reduce spam of browser bots

### ISSUE THREAD

**Issue by annevk** [w3c/web-platform-tests#5916]
We have #5611 about bot spam in general. If we add Edge and Safari bots that will increase the amount of spam. (I hear that's happening soon.) I was thinking that maybe as an intermediate workaround we could add the comments for the various bots directly after the PR is created and then silently update them later when the results are in.

**Comment by tobie** [comment]
You'll want to do add a workaround for wpt-pr-bot to wait for those to be ready, before it adds reviewers or this won't help at all.

I'm happy to take a reasonable pull request for this that doesn't make wpt-pr-bot brittle to those bots going down.

**Comment by bobholt** [comment]
I'm curious as to how this would help, because you're going to get the same number of emails. Is it just that the comments would come closer together in time?

I'm hesitant to work on something like this that will delay the real solution I'm currently working on (a single comment for all), and that requires workarounds to be placed in other infrastructure as @tobie mentions above.

I know that for the people receiving many notifications the notification spam is a pain, but I'm trying to understand here. Given that the number of owners receiving hundreds of notifications is theoretically small compared to the number of people contributing tests, what is not solvable by having people who have committed to being owners handling their own desired firehose level by setting mail filters (e.g. "from w3c-bots, mark as read" or "move to trash" or "label and archive" or whatever you need to do)?

**Comment by tobie** [comment]
> I'm curious as to how this would help, because you're going to get the same number of emails. Is it just that the comments would come closer together in time?

No. They would come before the owners are marked as reviewers, and thus no one would get those as emails.

That said, I think the email spam is only part of the problem. The comment spam on the actual thread is also a important issue.

**Comment by jgraham** [comment]
FWIW my understanding on @annevk's original request was that having 4 comments together is easier to handle in a workflow than 4 arriving at different times. Therefore I think all the additional complexity of updating Ganesh is unnecessary. But perhaps I misunderstood.

**Comment by tobie** [comment]
Oh well in that case…

**Comment by bobholt** [comment]
We moved to a single bot comment for build status. Closing.
