### ISSUE TITLE
"Chrome unstable" is a confusing job name

### ISSUE THREAD

**Issue by annevk** [w3c/web-platform-tests#5956]
Whenever I read this I think the results are unstable in Chrome.

**Comment by bobholt** [comment]
I see your point. This used to say "unstable channel", but I removed "channel" so that the Sauce tests wouldn't say "Safari channel" or "MicrosoftEdge channel."

I's an easy enough code change beyond coming up with phrasing that works for all cases, but it would require changing code in both web-platform-tests and prbuildbot and @sideshowbarker doing another simultaneous merge-and-deploy in both browsers. Is the header confusing enough that we should do that, or can it wait a couple of weeks for the single-comment functionality to wipe it away?

**Comment by annevk** [comment]
It can wait for sure.

**Comment by RByers** [comment]
@bobholt now that we [have the single-comment system](https://pulls.web-platform-tests.org/build/17458), can we fix this?  I.e. instead of saying "Chrome unstable" can it either have the specific version number like Safari and Edge do or just say "Chrome dev channel"?

**Comment by foolip** [comment]
I think this name comes from `JOB=stability SCRIPT=tools/ci/ci_stability.sh PRODUCT=chrome:unstable` because I couldn't find the string "Chrome Unstable" anywhere in this repo or https://github.com/w3c/wpt-pullresults.

The stability job will install https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb, so I installed that locally to confirm it's branded as "Dev" on the icon, and "65.0.3298.3 (Official Build) dev (64-bit)" in chrome://version/. So that's really what we should call it, the package name is probably because "dev" in debian package names usually means header files etc., or some other historical reason we don't need to care about.

I think the fix should be for the `install_chrome()` function in tools/ci/lib.sh to also accept "dev" as an argument and map that to unstable. The "unstable" bit will only be around the package name, everything else can call it "dev".
