### ISSUE TITLE
How are .https.-suffixed tests run?

### ISSUE THREAD

**Issue by dbates-wk** [w3c/web-platform-tests#6168]
What is responsible for running a test that requires being served with an HTTPS server? In particular, what infrastructure is responsible for running the test WebCryptoAPI/secure_context/crypto-subtle-secure-context-available.https.sub.html using an HTTPS server?

Briefly looking at the source for wptserve it neither has logic to redirect an HTTP request for a .https.-suffixed file to an HTTPS server nor has logic to error out if a .https.-suffixed test is requested over HTTP. I also do not see logic in wptrunner for handling .https.-suffixed files.

**Comment by dbates-wk** [comment]
We should also document the suffix .https. in test names to indicate that the test should be served using an HTTPS server.

**Comment by dbates-wk** [comment]
Additional remarks:

The Blink project first adopted the convention of running tests that contain ".https." using an HTTPS server in <https://chromium.googlesource.com/chromium/src/+/21b3fb22fb360dc6205bb8585d0a45046e245aec>.

**Comment by dbates-wk** [comment]
CC @bzbarsky, @mikewest

**Comment by jgraham** [comment]
https://github.com/w3c/web-platform-tests/blob/master/tools/manifest/item.py#L41 sets the https flag in the manifest from the filename, and wptrunner uses that to load the tests in the correct way.

**Comment by dbates-wk** [comment]
Thank you @jgraham.

**Comment by youennf** [comment]
> https://github.com/w3c/web-platform-tests/blob/master/tools/manifest/item.py#L41 sets the https flag in the manifest from the filename, and wptrunner uses that to load the tests in the correct way.

It does not seem to be the case for http://w3c-test.org/MANIFEST.json and its wptrunner.

It is also somehow bad that the infrastructure  (wptserver, test harness...) is not producing some warnings that HTTPS tests are actually run through HTTP.

**Comment by sideshowbarker** [comment]
> It does not seem to be the case for http://w3c-test.org/MANIFEST.json and its wptrunner.

http://w3c-test.org/MANIFEST.json doesn’t use `wptrunner` at all. Instead it only provides the web-based http://w3c-test.org/tools/runner/index.html, which is not `wptrunner` but instead a relatively very simple convenience tool. It is admittedly something that we collectively neglect as far as keeping it up to date with features that go into `wptrunner`—but that’s because it’s not being relied on by any browser projects for CI or production-level tasks in the way the `wptrunner` etc. automation is.

If keeping it up to date is higher priority for some reason for any particular browser project or anybody else, then I think whoever wants it prioritized higher and kept more up to date should take over ownership of it.

**Comment by jgraham** [comment]
Yeah, I'm tempted to say that it should move out into its own repository specifically so that it isn't avaiable on w3c-test.org until someone takes over maintaiance of it.
