### ISSUE TITLE
RTCPeerConnection-addIceCandidate.html causes race conditions

### ISSUE THREAD

**Issue by nils-ohlmeier** [w3c/web-platform-tests#6611]
RTCPeerConnection-addIceCandidate.html has several tests in it where the sequence is something like this:

`let ret = pc.addIceCandiddate();
 pc.close();
expect ret == reject`

Especially this test here: https://github.com/w3c/web-platform-tests/blob/master/webrtc/RTCPeerConnection-addIceCandidate.html#L574
is prone to test failures depending on the speed on the executing machine as it uses a timeout on top of the above sequence.

This is causing test failures in Mozilla's CI environment: https://bugzilla.mozilla.org/show_bug.cgi?id=1382972

I think these tests should be changed so that they look something like this:

`pc.close()
waitForSignalingStatetoReach(closed);
let ret = pc.addIceCandidate()
expect ret == rejected`

So you close the PeerConnection. Wait for the singaling state to actually reach 'closed' and then do what ever operation you need to check for against a closed PeerConnection.

**Comment by soareschen** [comment]
The original idea for the test was to test for the step _"1. If connection's [[isClosed]] slot is true, abort these steps."_ in _section 4.3.1.2 Enqueue an operation_. Because if that step was to reach first, the body of `addIceCandidate()` wouldn't have reach, so no iceCandidate would have been added and the promise wouldn't have resolve.

There were some discussions about race conditions of enqueue operations in w3c/webrtc-pc#1218. The consensus is that some of the steps in the specs are specifically crafted to cater for legacy behavior of current implementations.

Given that it is difficult to reason and test statements like "If connection's [[isClosed]] slot is true, then abort these steps.", I will remove the relevant tests until we have figured better ways to test such statements.

**Comment by jan-ivar** [comment]
FWIW I think it should be possible to test for [[isClosed]] in the common cases where the queue is empty. The only non-determinism would be invoking `addIceCandidate` from an `onicecandidate` callback, as those may happen at random.

**Comment by soareschen** [comment]
@jan-ivar When I have time I will read through the steps again and think of proper ways to test them. Will ask for help from you and @nils-ohlmeier to review the PR since we seems to have some different understanding of the semantics for enqueue operation and concurrent steps execution.
