### ISSUE TITLE
RTCPeerConnection-setLocalDescription.html has a race condition

### ISSUE THREAD

**Issue by nils-ohlmeier** [w3c/web-platform-tests#6612]
https://github.com/w3c/web-platform-tests/blob/master/webrtc/RTCPeerConnection-setLocalDescription.html#L158 is only asking for a race condition as you can see in Mozilla's CI system: https://bugzilla.mozilla.org/show_bug.cgi?id=1383069

I'm not aware of any spec language requiring the browser to wait with the execution of 'setLocalDescription()' to make sure that a subsequent 'close()' gets executed first.

Depending on a lot of factors this test might either succeed or fail. As I'm not aware of any way how you could ensure that the 'close()' call will get executed before the 'setLocalDescription()' call I think this tests needs to be removed.

**Comment by soareschen** [comment]
The original idea is that step 2.2.1. in _section 4.3.1.6 Set the RTCSessionSessionDescription_ is executed after queuing a task.

> If description is applied successfully, the user agent _MUST queue a task that runs the following steps_:

So the queued steps are supposed to executed only after returning to the event loop. And since `close()` is synchronous, it is executed first.

Anyway there were some related discussions about race conditions in w3c/webrtc-pc #1218. The consensus is that some of the steps in the specs are specifically crafted to cater for legacy behavior of current implementations.

Given that it is difficult to reason and test statements like _"If connection's [[isClosed]] slot is true, then abort these steps."_, I will remove the relevant tests until we have figured better ways to test such statements.

**Comment by soareschen** [comment]
Closed with #6616.
