### ISSUE TITLE
Payment allowed-by-feature-policy test

### ISSUE THREAD

**Issue by MSFTkihans** [w3c/web-platform-tests#6812]
https://github.com/w3c/web-platform-tests/blob/master/payment-request/payment-allowed-by-feature-policy-attribute-redirect-on-load.https.sub.html
This test relies on the allow attribute of iframe, which isn't implemented in all browsers and doesn't seem to be part of the W3C spec for iframes. (see https://github.com/w3c/web-platform-tests/blob/master/feature-policy/resources/featurepolicy.js, line 31)
It would likely be preferable to use allowPaymentRequest, which is implemented in all browsers and is part of the spec.

**Comment by marcoscaceres** [comment]
@MSFTkihans, note that PaymentRequest uses WHATWG HTML (not the W3C one), which does include the iframe attribute: 

https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-allowpaymentrequest

**Comment by MSFTkihans** [comment]
Yes, the test itself relies on iframe.allow being an attribute, which is a non-standard attribute.

**Comment by marcoscaceres** [comment]
@MSFTkihans, really sorry, I'm confused by what you mean by non-standard? `allowpaymentrequest` is standard - [it's part of the HTML spec](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-allowpaymentrequest)? 

If you mean "non-standard" because it's not in W3C HTML 5.x, the whole of Payment Request spec depends on WHATWG HTML (not the W3C one!) and other WHATWG specs.  As such, we make no normative reference to the W3C HTML (because it's obsolete) - and we expect user agents to implement what is in the WHATWG HTML spec, not the W3C one. 

Apologies for the confusion, many W3C members are working towards preventing further confusion on the W3C side by having them stop publishing the W3C HTML spec (which is obsolete, and should be ignored).

**Comment by marcoscaceres** [comment]
Closing as invalid.

**Comment by MSFTkihans** [comment]
@marcoscaceres Sorry, my phrasing was possibly unclear. I was not referring to the allowpaymentrequest attribute. I was referring the allow attribute of iframe. Please refer to at https://github.com/w3c/web-platform-tests/blob/master/feature-policy/resources/featurepolicy.js, line 31, which references the attribute

**Comment by marcoscaceres** [comment]
No problem. Thanks for clarifying. I'll take another look.

**Comment by marcoscaceres** [comment]
I've moved the feature policy tests out. Sorry about the confusion on my part, @MSFTkihans  😺
