### ISSUE TITLE
Cross-origin Payment Request in Payment Allowed By Feature Policy

### ISSUE THREAD

**Issue by MSFTkihans** [w3c/web-platform-tests#6899]
In https://github.com/w3c/web-platform-tests/blob/master/payment-request/payment-allowed-by-feature-policy.https.sub.html#L32
The test expects a payment request to succeed when launched from a cross-origin iframe and without the `allowpaymentrequest` attribute. This is against the W3C spec for web payment requests, so it fails for browsers that implement the spec. The function passed in the `async_test` call should be `expect_feature_unavailable_default`.

**Comment by marcoscaceres** [comment]
We need to move these tests out to a future version of the payments spec. This is not part of v1.

**Comment by marcoscaceres** [comment]
@rsolomakhin, @igrigorik, @mikewest, a bit of background: It seems that "feature-policy" related tests ended up in the Payment Request repo. However, Payment Request V1 doesn't itself depend on feature policy (though it will be nice to do so in a future version). 
 
I'm wondering if we should move feature-policy tests out of the Payment Request folder, and into a "feature-policy" folder instead (for the reason that neither Gecko or Edge support it, AFAIK, and because it's not in scope for Payment Request V1)? 

Do you have thoughts/opinions about what we should do?

**Comment by marcoscaceres** [comment]
I should clarify, I believe the tests came from Blink repository.

**Comment by rsolomakhin** [comment]
That sounds reasonable. Thank you, @marcoscaceres.

**Comment by mikewest** [comment]
https://github.com/w3c/web-platform-tests/tree/master/feature-policy exists, and seems like the right place for these tests. +@clelland as I don't know Raymes' username. :)

**Comment by marcoscaceres** [comment]
Ok, PR sent:
https://github.com/w3c/web-platform-tests/pull/7329 

The bot tells me that no one currently owns the feature-policy tests. 

Any volunteers? I'm adding @clelland as owner, as he is spec editor.

**Comment by clelland** [comment]
@marcoscaceres That seems like it would make sense, thanks.

In Blink, we've been trying to separate the tests for feature policy itself (does the browser recognize the header, and the `allow` attribute; does it combine policies correctly between frames; etc.) from the tests for each individual feature under its control.

I would normally think of a test which verifies the behavior of PaymentRequest under different policies to be a PaymentRequest test, rather than a feature policy test, but it's a bit muddy, and complicated by the fact that feature policy is still a draft, and unsupported in other engines. I'm happy to have those tests live for now in /feature-policy/, if that's the best place for them.

**Comment by marcoscaceres** [comment]
> I would normally think of a test which verifies the behavior of PaymentRequest under different policies to be a PaymentRequest test, rather than a feature policy test,

Normally, I would agree with you - but we have been working with the assumption that things in the root folders are tests related to the conformance requirements of particular specs (hence, "payment-request" only tests the requirements in the Payment Request spec, which does not include any conformance requirements relating to feature policy... not yet, anyway 😉).  

>  but it's a bit muddy, and complicated by the fact that feature policy is still a draft, and unsupported in other engines. I'm happy to have those tests live for now in /feature-policy/, if that's the best place for them.

For now, that would be great. A few of us would like to see Feature Policy be part of a future version of the Payment Request (PR) API - but we'd like to first get PR to Recommendation status with the smaller test suite (if all goes according to plan, that should happen by the end of the year).

**Comment by marcoscaceres** [comment]
Here is the bug for adding Feature Policy support to "V2" of Payment Request: https://github.com/w3c/payment-request/issues/600
