### ISSUE TITLE
Why does the manifest include .svg files as testharness tests?

### ISSUE THREAD

**Issue by domenic** [w3c/web-platform-tests#7313]
For example, `dom/nodes/Element-childElement-null-svg.svg` is noted as a testharness.js test. This seems bad.

**Comment by gsnedders** [comment]
Why? Because it contains `<h:script src="/resources/testharness.js"/>`, where `h` is bound to the HTML namespace.

I don't remember the origin of why we let SVG files be tests, but it may simply be the fact we allow arbitrary XML files to be tests and then why exclude one specific subset.

In a sense, the biggest problem is the fact we don't append any result table if `!document.body`, and hence we don't get any result except in HTML/XHTML.

The full list of `*.svg` test harness tests, FWIW, is:

```
dom/nodes/Document-constructor-svg.svg
dom/nodes/Element-childElement-null-svg.svg
dom/nodes/Element-childElementCount-dynamic-add-svg.svg
dom/nodes/Element-childElementCount-dynamic-remove-svg.svg
dom/nodes/Element-childElementCount-nochild-svg.svg
dom/nodes/Element-childElementCount-svg.svg
dom/nodes/Element-firstElementChild-entity.svg
dom/nodes/Element-firstElementChild-namespace-svg.svg
dom/nodes/Element-firstElementChild-svg.svg
dom/nodes/Element-lastElementChild-svg.svg
dom/nodes/Element-nextElementSibling-svg.svg
dom/nodes/Element-previousElementSibling-svg.svg
dom/nodes/Element-siblingElement-null-svg.svg
```

(There's many more reftests.)

**Comment by domenic** [comment]
Huh, interesting. Are they working as intended?

When I open e.g. http://w3c-test.org/dom/nodes/Document-constructor-svg.svg I don't see anything in Edge in the console, which I would have expected since Edge does not implement the Document() constructor.

Of course, maybe Edge just doesn't do script execution in SVG at all... I also tried setting a breakpoint in Chrome, and it wasn't hit, but again, maybe the debugger doesn't like SVGs...

**Comment by gsnedders** [comment]
At least `dom/nodes/Element-childElement-null-svg.svg` seems to run to completion in Chrome (see the `#__testharness__results__` element that gets added with the one result). And a breakpoint in the test function is hit.

http://wpt.fyi/dom/nodes shows a bunch of results for all of them, which also implies they're working.

**Comment by domenic** [comment]
Great, OK! Working as intended then, I suppose!

**Comment by gsnedders** [comment]
I'm happy to say we should add a results table to non-HTML documents, unless someone objects, FWIW.
