### ISSUE TITLE
Test metadata should be in test file, not in filename

### ISSUE THREAD

**Issue by alvestrand** [w3c/web-platform-tests#7913]
The "must be tested using HTTPS" flag is currently encoded by naming the files with .https.html.
It's been suggested to mark provisional tests by naming them as .provisional.html.
Putting information about the test into the test identifier (name) is bad information management practice, and having multiple orthogonal pieces of metadata inside it makes it even worse.
Can we put this information inside the test instead?

(putting this into an infra issue as per a conversation with @foolip)

**Comment by foolip** [comment]
Aside: provisional tests are called tentative and now documented in http://web-platform-tests.org/writing-tests/file-names.html

@alvestrand, to spell out the concern, is it that renaming files when the metadata changes is annoying?

There is *some* metadata that's in the file itself, like [`<link rel=match>`](http://web-platform-tests.org/writing-tests/reftests.html) or the inclusion of `/resources/testharness.js` being the thing that determines what the test type is. @jgraham, are there other things?

One tricky thing with in-file metadata for https and tentative is that it couldn't be the same mechanism for foo.html and foo.any.js, for example. The natural place in HTML would be `<meta>`, but what then for JS?

**Comment by jgraham** [comment]
I'm not sure why this is "bad information management practice". Putting metadata (in the form of a file extension) inside a file is extremely common and, as @foolip points out the filename is the only place we can put this information in a format-independent way. In general putting too much information inside the file is problematic because:
* It's slower to read (we need to parse the whole file rather than just looking at the filename)
* It's harder for users to find.
* We need to invent an encoding that can be used across multiple file types (HTML, Python, Javascript, maybe others in the future)
* It puts constraints on the actual test which can be significant when testing implementations (e.g. if you are trying to test the behaviour of a file with exactly one `meta` tag that's hard to do if all tests require meta tags just to function.
* Using data inside the file absolutely depends on the manifest being available.

That said there isn't a totally principled split between data we keep in the path and data we keep in the file, but most individual parts have a good reason for being where they are. At the moment we keep the following data in the path:

* The protocol (i.e. `.https.`). This means that someone loading a test can figure out which protocol to use without having to examine the file contents (or the manifest). That's a significant win for ad-hoc testing.
* Various pieces of information that control the test type including the `-manual` flag and special directory names like `support`, `resources` and `tools`. These are important optimisations to ensure we don't have to process every file when generating the manifest.
* The `-ref` flag. This is mostly optional and for backward compatibility, since we actually figure out references from in-file metadata.
* The flags for generating tests (`.any.`, `.worker.`, `.window.`, etc.). These apply to js files, and putting this data in the name helps make the generated paths used by the http server look like the file name. They also indicate to users that the path cannot be loaded directly to generate a test.
* The `stub` flag. This is mostly a failed experiment, but indicates that the file isn't yet a real test, so is like the `-manual` flag.
* The `tentative` flag. This is perhaps the odd one out here, but one can argue that this data must be clearly exposed to users, and the filename is the best place to do that.
* The file type (i.e. `.html`, `.css`, etc.). Obviously, but nevertheless.

The following data goes in the file:

* Whether a `.html` file is a `testharness` test. This reuses data that has to be in the file for the test to work, so it avoids explicit metadata.
* References for reftests with `<meta rel=[mis]match]>`. This allows multiple files to share a reference which is a significant performance optimistation vs the `-ref` convention (at the expense of a larger manifest and slower manifest generation).
* Metadata indicating that the timeout is long. This is only used by the test runner, so putting it in the file seems fine.
* The viewport size, dpi, and device pixel ratio. This is rarely used (and not really supported by the runners at the moment), but it's probably only going to be used by test harnesses.
* Any variants for the test (i.e. additional query strings that can be used to get different test versions). Putting this data in the file itself is sub-optimal, since it would ideally be exposed clearly to users, but there simply isn't a reasonable way to put it anywhere else. It's also a rarely used feature.
* Additional scripts to load for `.[worker|any|window].js` scripts.

For `.tentative.` in particular I could buy the argument that having to rename the file to remove the tag is relatively annoying since it can break comparisons, and therefore we should use a flag in the file instead of in the filename. But other than that, I think there's probably a certain amount of personal preference here and I am extremely reluctant to start changing how things work without some very compelling reasons.

**Comment by foolip** [comment]
For tentative tests, I would be fine with switching that to in-band metadata to avoid renaming back and forth. It would have to be something that works at least HTML and JavaScript files, maybe as simple as the string "tentative" appearing somewhere in the file, although that might be too subtle.

@alvestrand, I assume the piece of metadata you're most interested in is HTTPS, because a bunch of tests using getUserMedia() had to be renamed?

**Comment by jgraham** [comment]
I would be quite opposed to changing the system for encoding https. I think the fact that it appears in the path is very useful to users trying to load tests, and I think it's uncommon for https tests to suddenly become non-https, so renaming once the tests work should be rare. I assume something external changed here e.g. the feature was made https-only?

**Comment by foolip** [comment]
No, the tests originally just didn't work in any automated running environment, it was after they were imported into Chromium and @alvestrand tried to get more of them passing that the problem became obvious.

**Comment by foolip** [comment]
OK, so I think the only concrete here that we might do is to move tentative from filename to the file, but we don't know how for .any.js. @mikewest, as the pioneer in tentative tests, have you found this to be a nuisance, and would you prefer the information to be in the files?

**Comment by foolip** [comment]
One thing that'd be tricky with putting it in the file is surfacing this special status in wpt.fyi. Nothing about the test results would suggest that it's tentative, so we'd have to style it differently presumably.

This has the roadmap label now. When this comes up in triage next time, if there's nothing concrete we can agree on, then we should close the issue.

**Comment by mikewest** [comment]
*shrug* I don't have any problem with `tentative` showing up in the filename. I had a slight preference for putting `tentative` into the path instead (via a top-level `tentative` directory, or a `tentative` subdirectory in an existing directory), but I think the filename mechanism makes it fairly straightforward for vendors to decide whether or not it's safe to ignore a test failure. I would not be horribly, terribly sad if y'all decided to move it into the file itself, but I personally have no positive reason to do so.

P.S. I do have strong feelings about `.https.` for the reasons @jgraham noted above: that suffix makes it trivial to determine the tests' URL from the filename. I'm using it in scripts to run tests locally, it's used in the browser-based test runner as well. Enabling that kind of _a priori_ decision about the test URL seems to me to be pretty valuable; I'd hate to lose it.

**Comment by foolip** [comment]
Thanks Mike, I'll go ahead and close this. If we have feedback from others using tentative tests that the current setup is frustrating we can revisit. @alvestrand, are you OK with this outcome?

**Comment by youennf** [comment]
From WebKit infrastructure perspective, https suffix is very convenient and we would prefer to keep it like that.
This is actually in use in all WebKit LayoutTests, not only imported WPT ones.
