### ISSUE TITLE
Add new semantic HTML5 element "container"

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [w3c/web-platform-tests#8034]
**I dont know where to put thie Req.**

In **99.9999%** of the times you use `container` to wrap content (one or more in a page) - center + Add right & left space. Why thier is no wrapper element (same as div and section - block element)? Without semantic meaning (like div or span)!! **but** when you code its more easy to read code looks like this (more semantic, clean code):
```
<container>
        <h1>hello</h1>
</container>
```

Instead of this !
```
<div class="container">
        <h1>hello</h1>
</div>
```
The name **container** is the same for [boostrap ](https://getbootstrap.com/docs/3.3/css/#overview-container), [uikit ](https://getuikit.com/docs/container), [boolma ](https://bulma.io/documentation/layout/container/), [materializecss](http://materializecss.com/grid.html) and most other frameworks, and even on [WIX ](https://support.wix.com/en/article/adding-a-container-box), [webflow ](https://university.webflow.com/article/container)and other web builders - in other words --> this is very **universal** term in web design.

**Comment by snuggs** [comment]
@Ezra-Siton-UIX I believe all your needs would be covered with `<div>` yes?  `<container>` feels a little bit of CSS _(conventions)_ encroaching into HTML tag ontology. And `<div>`'s main intent and purposes are for just the reason you use. Perhaps your reasoning is because many authors still suffer from "divitus" thus making the intended purpose of the `<div>` more vague.

Secondly the `<section>` element should never be used for a generic container based on the following portion of [the spec](https://html.spec.whatwg.org/multipage/sections.html#the-section-element):

> The section element is not a generic container element. When an element is needed only for styling purposes or as a convenience for scripting, authors are encouraged to use the div element instead. A general rule is that the section element is appropriate only if the element's contents would be listed explicitly in the document's outline.

Regardless, the `web-platform-tests` may not be the place to birth a new tag suggestion.

**Comment by Ezra-Siton-UIX** [comment]
OK. Where is the best place to put this issue. I like your answer - you add nice points.

**Comment by gsnedders** [comment]
See <https://whatwg.org/faq#adding-new-features>.

**Comment by snuggs** [comment]
Thanks @gsnedders. I didn't have an answer nor who to ping. 🙏
