### ISSUE TITLE
css/CSS2/colors/color-030.xht is wrong per Color 4

### ISSUE THREAD

**Issue by csnardi** [w3c/web-platform-tests#8828]
Color 4 added 4-digit and 8-digit hex colors, but css/CSS2/colors/color-030.xht tests a 4-digit hex color as an invalid value. As a result, it is failing on platforms that have added 4-digit hex colors.

Since this test is part of the CSS2 test suite, it is valid per CSS2. However, since it should fail after Color 4 has been implemented, I think removal of the test case is probably appropriate.

**Comment by gsnedders** [comment]
> Since this test is part of the CSS2 test suite, it is valid per CSS2. However, since it should fail after Color 4 has been implemented, I think removal of the test case is probably appropriate.

The test isn't valid per CSS2, because CSS2 states: "A user agent conforming to a future CSS specification may accept one or more of the other rules as well."

And given we have an existence proof of a future CSS specification defining this syntax, we can conclude CSS 2.1 allows two behaviours:

 * ignoring the rule
 * handling it per later levels of CSS

(The actual language in the spec is a bit weird, because we have a MAY overriding a MUST.)

That said, I agree that just dropping the test is the right option.
