### ISSUE TITLE
[css-counter-styles-3] armenian/css3-counter-styles-008.html out of scope

### ISSUE THREAD

**Issue by liamquin** [w3c/web-platform-tests#9741]
This test has values 10,000 and 10,001 for the list counter but the spec says the range limit is 9999.

The test assumes the numbers "work", but presumably it should be an error, or the result is possibly undefined. Either the spec should allow higher numbers or the test should be removed (or moved to level 4 perhaps).

**Comment by liamquin** [comment]
Actually looks like it's trying to test fallback in the presence of @range. So the problem is that the spec should say more clearly why Armenian numbers are limited to 9999 in the normative default stylesheet.

**Comment by kriti21** [comment]
I want to work on this issue. @liamquin can you please elaborate what change is needed here. I do not understand what is **spec** in your comment above.

**Comment by kriti21** [comment]
@liamquin Please review my PR above and guide me if I have got it right. Thanks :)

**Comment by liamquin** [comment]
@kriti21no, the working group has to decide on what to do in this case with the range property. Falling back to English outside the range is insane, and also unsupported by actual browsers.

**Comment by kriti21** [comment]
Should I close my PR in that case ? @liamquin

**Comment by liamquin** [comment]
On Fri, 2018-04-06 at 15:38 +0000, Kriti Rohilla wrote:
> Should I close my PR in that case ? @liamquin 

that would be fine, as it'll end up being a different approach one way
or the other - thanks!
> 
-- 
Liam Quin, W3C, http://www.w3.org/People/Quin/
Staff contact for Verifiable Claims WG, SVG WG, XQuery WG
Improving Web Advertising: https://www.w3.org/community/web-adv/
Personal: awesome vintage art: http://www.fromoldbooks.org/

**Comment by r12a** [comment]
@liamquin I believe there's a discussion about Armenian in the CSS or i18n lists from some years ago. If memory serves, there was an unresolved disagreement about the expected format of numbers above 9,999. This is not unusual. (An in fact, resolution of that disagreement may have only extended the range, rather than produced an infinite range.)

The @range feature is normally used for counter styles that by definition or cultural tradition don't allow negative numbers. Note that these are _additive_ systems, not numeric. It is also often the case that the rules for a given counting method simply don't specify how to count past a certain number.  

The @range feature allows us to use useful ranges of the counter-style, but essentially indicates that if you want to use this counter style for more than, in this case, 9,999 items 
1. the results may be meaningless, ambiguous, or confusing
2. you'd probably better use a different counter style
3. if you do use this counter style and inadvertently go past the end of the range, then at least you'll see something predictable and something that clearly indicates that you are in uncharted territory.

In the meantime, and for a very large percentage of use cases, the counter style works fine if you stay within the limits.

The test in question is checking that the browser follows the spec, and falls back to the decimal counter outside the range. As such it is a perfectly valid test, imo. So i think this issue is a red herring, and should be closed (with the related PR).

**Comment by liamquin** [comment]
[closing, as if this doesn't bother i18n i'm ok with it and withdraw the comment]
